-- MySQL Script generated by MySQL Workbench
-- Sat Apr 14 12:27:41 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema myblog
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema myblog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `myblog` DEFAULT CHARACTER SET utf8 ;
USE `myblog` ;

-- -----------------------------------------------------
-- Table `myblog`.`Admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myblog`.`Admin` ;

CREATE TABLE IF NOT EXISTS `myblog`.`Admin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `sault` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idAdmin_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myblog`.`Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myblog`.`Category` ;

CREATE TABLE IF NOT EXISTS `myblog`.`Category` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL COMMENT '博客分类名称',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myblog`.`Tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myblog`.`Tag` ;

CREATE TABLE IF NOT EXISTS `myblog`.`Tag` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL COMMENT '博客标签名\n',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idTag_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myblog`.`Article`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myblog`.`Article` ;

CREATE TABLE IF NOT EXISTS `myblog`.`Article` (
  `id` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  `date` DATE NULL,
  `visitTotal` INT(5) NULL DEFAULT 0,
  `commentTotal` INT(5) NULL DEFAULT 0,
  `imgSrc` VARCHAR(45) NULL,
  `content` TEXT(100000) NULL,
  `isPlublished` INT NULL DEFAULT 0,
  `foreword` VARCHAR(255) NULL,
  `Category_id` INT NOT NULL,
  `Admin_id` INT NOT NULL,
  `Tag_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Article_Category_idx` (`Category_id` ASC),
  INDEX `fk_Article_Admin1_idx` (`Admin_id` ASC),
  INDEX `fk_Article_Tag1_idx` (`Tag_id` ASC),
  CONSTRAINT `fk_Article_Category`
    FOREIGN KEY (`Category_id`)
    REFERENCES `myblog`.`Category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Article_Admin1`
    FOREIGN KEY (`Admin_id`)
    REFERENCES `myblog`.`Admin` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Article_Tag1`
    FOREIGN KEY (`Tag_id`)
    REFERENCES `myblog`.`Tag` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myblog`.`Comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myblog`.`Comment` ;

CREATE TABLE IF NOT EXISTS `myblog`.`Comment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL COMMENT '评论人的昵称',
  `email` VARCHAR(120) NULL COMMENT '评论人的邮箱',
  `website` VARCHAR(255) NULL COMMENT '评论人的网址',
  `content` VARCHAR(255) NULL COMMENT '评论内容',
  `date` DATE NULL COMMENT '评论时间',
  `Article_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idComment_UNIQUE` (`id` ASC),
  INDEX `fk_Comment_Article1_idx` (`Article_id` ASC),
  CONSTRAINT `fk_Comment_Article1`
    FOREIGN KEY (`Article_id`)
    REFERENCES `myblog`.`Article` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myblog`.`Replying`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myblog`.`Replying` ;

CREATE TABLE IF NOT EXISTS `myblog`.`Replying` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL COMMENT '回复人名称',
  `content` VARCHAR(255) NULL COMMENT '回复的内容',
  `date` DATE NULL COMMENT '回复时间',
  `Comment_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idComment_UNIQUE` (`id` ASC),
  INDEX `fk_Replying_Comment1_idx` (`Comment_id` ASC),
  CONSTRAINT `fk_Replying_Comment1`
    FOREIGN KEY (`Comment_id`)
    REFERENCES `myblog`.`Comment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
