-- MySQL Script generated by MySQL Workbench
-- Sun Apr  1 11:39:57 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema imgManagement
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema imgManagement
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `imgManagement` DEFAULT CHARACTER SET utf8 ;
USE `imgManagement` ;

-- -----------------------------------------------------
-- Table `imgManagement`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `imgManagement`.`User` ;

CREATE TABLE IF NOT EXISTS `imgManagement`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `UserName` VARCHAR(45) NULL,
  `UserPassword` VARCHAR(45) NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `idUser_UNIQUE` (`idUser` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imgManagement`.`Folder`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `imgManagement`.`Folder` ;

CREATE TABLE IF NOT EXISTS `imgManagement`.`Folder` (
  `idFolder` INT NOT NULL AUTO_INCREMENT,
  `FolderName` VARCHAR(45) NULL,
  PRIMARY KEY (`idFolder`),
  UNIQUE INDEX `idFolder_UNIQUE` (`idFolder` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imgManagement`.`Img`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `imgManagement`.`Img` ;

CREATE TABLE IF NOT EXISTS `imgManagement`.`Img` (
  `idImg` INT NOT NULL AUTO_INCREMENT,
  `ImgName` VARCHAR(45) NULL,
  `ImgUrl` VARCHAR(255) NULL,
  `Folder_idFolder` INT NOT NULL,
  PRIMARY KEY (`idImg`),
  UNIQUE INDEX `idImg_UNIQUE` (`idImg` ASC),
  INDEX `fk_Img_Folder_idx` (`Folder_idFolder` ASC),
  CONSTRAINT `fk_Img_Folder`
    FOREIGN KEY (`Folder_idFolder`)
    REFERENCES `imgManagement`.`Folder` (`idFolder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
